package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Configuracion_ventana extends VerticalLayout {
	protected VerticalLayout cabecera;
	protected Button atrasB;
	protected Label configuracionL;
	protected VerticalLayout ajustes_notificaciones;
	protected Label todasL;
	protected CheckBox todasCH;
	protected Label seguirL;
	protected CheckBox seguirCH;
	protected Label meGustaL;
	protected CheckBox meGustaCH;
	protected Label solicitudSeguirL;
	protected CheckBox solicitudSeguirCH;
	protected Label comentariosL;
	protected CheckBox comentariosCH;
	protected Label eliminacionPublicacionL;
	protected CheckBox eliminacionPublicacionCH;
	protected VerticalLayout privacidad;
	protected CheckBox hacerPrivadaCH;
	protected Label hacerPivadaL;
	protected CheckBox ocultarSeguidorSeguidoCH;
	protected Label ocultarSeguidorSeguidoL;
	protected Button darseBajaB;
	protected Button verListaBloqueadosB;
	protected Button cerrarSesionB;
	protected VerticalLayout layout_confirmar;
	protected Label mensajeL;
	protected Button aceptarB;
	protected Button cancelarB;
	protected HorizontalLayout menu_inferior;
	protected Button paginaPrincipalB;
	protected Button buscarB;
	protected Button publicarB;
	protected Button verNotificacionesActividadesB;
	protected Button verêrfilPropioB;

	public Configuracion_ventana() {
		Design.read(this);
	}
}
