package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Editar_perfil_ventana extends VerticalLayout {
	protected Button atrasB;
	protected Label editarPerfilL;
	protected Image imageUsuarioI;
	protected Label nombreUsuarioL;
	protected Label nombreL;
	protected TextField nombreTF;
	protected Label apellidoL;
	protected TextField apellidoTF;
	protected Label nombreUsuarioL1;
	protected HorizontalLayout menu_inferior;
	protected Button paginaPrincipalB1;
	protected Button buscarB1;
	protected Button publicarB1;
	protected Button verNotificacionesActividadesB1;
	protected Button verêrfilPropioB;

	public Editar_perfil_ventana() {
		Design.read(this);
	}
}
