package MDS2.instagual;

public class Eliminar_comentario_de_publicacion extends Eliminar_comentario_de_publicacion_propia {
	public Ver_detalles_de_publicacion_admin _ver_detalles_de_publicacion_admin;
}