package MDS2.instagual;

public class Publicacion_propia_de_otro_usuario {
	//private Image _imagenMuestraI;
	public Lista_de_publicaciones_del_usuario _lista_de_publicaciones_del_usuario;
	public Ver_detalles_de_publicacion_vista_usuario_registrado _ver_detalles_de_publicacion_vista_usuario_registrado;
}