package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Publicar_ventana extends VerticalLayout {
	protected VerticalLayout contenedor_barra;
	protected HorizontalLayout barra_superior;
	protected Image atrasB;
	protected Button galeriaB;
	protected Button publicarB1;
	protected VerticalLayout imagen_video_layout;
	protected Image elemento_imagen;
	protected GridLayout galeria_layout;
	protected VerticalLayout descripcion_layout;
	protected TextArea descripcionTA;
	protected VerticalLayout menu_inferior_layout;
	protected HorizontalLayout contenedor_horizontal;
	protected HorizontalLayout inicio;
	protected Image paginaPrincipalB;
	protected HorizontalLayout buscar;
	protected Image buscarB;
	protected HorizontalLayout publicar;
	protected Image publicarB;
	protected HorizontalLayout notificaciones;
	protected Image verNotificacionesActividadesB;
	protected HorizontalLayout perfil;
	protected Image verPerfilPropioB;

	public Publicar_ventana() {
		Design.read(this);
	}
}
