package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Recuperar_password_ventana extends VerticalLayout {
	protected VerticalLayout cabecera;
	protected Image logo_instagualI;
	protected VerticalLayout recuperarLayout;
	protected Label mensajeL;
	protected TextField correoTF;
	protected VerticalLayout mitad2;
	protected Button cancelarB;
	protected Button recuperarPasswordB;

	public Recuperar_password_ventana() {
		Design.read(this);
	}
}
