package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registrado_con_exito_ventana extends VerticalLayout {
	protected VerticalLayout cabecera;
	protected Image logo_instagualI;
	protected VerticalLayout bienvenidoLayout;
	protected Label mensajeL;
	protected Image inicioB;
	protected VerticalLayout menu_inferior_layout;
	protected HorizontalLayout contenedor_horizontal;
	protected HorizontalLayout inicio;
	protected Button paginaPrincipalB;
	protected HorizontalLayout buscar;
	protected Button buscarB;
	protected HorizontalLayout publicar;
	protected Button publicarB;
	protected HorizontalLayout notificaciones;
	protected Button verNotificacionesActividadesB;
	protected HorizontalLayout perfil;
	protected Button verPerfilPropioB;

	public Registrado_con_exito_ventana() {
		Design.read(this);
	}
}
