package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registrarse_ventana extends VerticalLayout {
	protected VerticalLayout cabecera;
	protected Image logo_instaI;
	protected VerticalLayout inferior;
	protected Label registrarseL;
	protected TextField correoTF;
	protected PasswordField passwordTF;
	protected Button registrarseB;
	protected Button cancelarB;

	public Registrarse_ventana() {
		Design.read(this);
	}
}
