package MDS2.instagual;

public class Usuario_que_dio_me_gusta {
	private Usuario _usuario;
	public Lista_de_usuarios_que_dieron__me_gusta_ _lista_de_usuarios_que_dieron__me_gusta_;
	public Ver_perfil_de_usuario_vista_no_registrado_lista_de_usuarios_que_dieron_me_gusta _ver_perfil_de_usuario_vista_no_registrado_lista_de_usuarios_que_dieron__me_gusta_;
}