package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_perfil_de_usuario_vista_perfil_propio_ventana extends VerticalLayout {
	protected HorizontalLayout cabecera;
	protected Label nombreUsuarioL;
	protected Button editarPerfilB;
	protected Label seguidoresL;
	protected Label seguidosL;
	protected HorizontalLayout botones_tab;
	protected HorizontalLayout menu_inferior;
	protected Button paginaPrincipalB;
	protected Button buscarB;
	protected Button publicarB;
	protected Button verNotificacionesActividadesB;
	protected Button verêrfilPropioB;

	public Ver_perfil_de_usuario_vista_perfil_propio_ventana() {
		Design.read(this);
	}
}
