package MDS2.instagual;

public class Ver_detalles_de_publicacion_admin extends Ver_detalles_de_publicacion {
	public Buscar_vista_admin _buscar_vista_admin;
	public Eliminar_publicacion _eliminar_publicacion;
	public Eliminar_comentario_de_publicacion _eliminar_comentario_de_publicacion;
}