package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_lista_de_comentarios_vista_admin_ventana extends VerticalLayout {
	protected HorizontalLayout cabecera;
	protected Image instaTextI;
	protected Button atrasB;
	protected TextField busquedaTF;
	protected Button buscarB;
	protected Button cerrar_sesion_admin;
	protected HorizontalLayout detalle_publicacion;
	protected Label descripcionL;
	protected HorizontalLayout usuarioPublicadorU;
	protected Label nombreUsuarioL;
	protected Button verUsuarioB1;
	protected Button eliminarComentarioB;
	protected Label comentarioL;
	protected HorizontalLayout usuarioPublicadorU1;
	protected Label nombreUsuarioL1;
	protected Button verUsuarioB;
	protected Button eliminarComentarioB1;
	protected Label comentarioL1;
	protected HorizontalLayout eliminacionPublicacion;
	protected Label mensajeL;
	protected Button confirmarEliminacionB;
	protected Button cancelarEliminacionB;

	public Ver_lista_de_comentarios_vista_admin_ventana() {
		Design.read(this);
	}
}
