package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_lista_de_quien_dio_me_gusta_ventana extends VerticalLayout {
	protected VerticalLayout contenedor_barra;
	protected Button atrasB;
	protected Image logo_instagualI;
	protected Label bloqueadosL;
	protected VerticalLayout comentarios_layout;
	protected Image usuarioI;
	protected Label nombreUsuarioL;
	protected Image usuarioI1;
	protected Label nombreUsuarioL1;
	protected Image usuarioI2;
	protected Label nombreUsuarioL2;
	protected Image usuarioI3;
	protected Label nombreUsuarioL3;
	protected Image usuarioI4;
	protected Label nombreUsuarioL4;
	protected Image usuarioI5;
	protected Label nombreUsuarioL5;
	protected VerticalLayout menu_inferior_layout;
	protected HorizontalLayout contenedor_horizontal;
	protected HorizontalLayout inicio;
	protected Button paginaPrincipalB;
	protected HorizontalLayout buscar;
	protected Button buscarB;
	protected HorizontalLayout publicar;
	protected Button publicarB;
	protected HorizontalLayout notificaciones;
	protected Button verNotificacionesActividadesB;
	protected HorizontalLayout perfil;
	protected Button verPerfilPropioB;

	public Ver_lista_de_quien_dio_me_gusta_ventana() {
		Design.read(this);
	}
}
