package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_pagina_principal_ventana extends VerticalLayout {
	protected VerticalLayout contenedor_barra;
	protected Image logo_instagualI;
	protected VerticalLayout comentarios_layout;
	protected Image usuarioI1;
	protected Label nombreUsuarioL1;
	protected Image publicacionI;
	protected VerticalLayout comentariosLayout1;
	protected Button meGustasB;
	protected Label numeroMeGustaL;
	protected Image usuarioI12;
	protected Label nombreUsuarioL12;
	protected Image publicacionI2;
	protected VerticalLayout comentariosLayout12;
	protected Button meGustasB2;
	protected Label numeroMeGustaL2;
	protected VerticalLayout menu_inferior_layout;
	protected HorizontalLayout contenedor_horizontal;
	protected HorizontalLayout inicio;
	protected Button paginaPrincipalB;
	protected HorizontalLayout buscar;
	protected Button buscarB;
	protected HorizontalLayout publicar;
	protected Button publicarB;
	protected HorizontalLayout notificaciones;
	protected Button verNotificacionesActividadesB;
	protected HorizontalLayout perfil;
	protected Button verPerfilPropioB;

	public Ver_pagina_principal_ventana() {
		Design.read(this);
	}
}
