package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_lista_de_comentarios_ventana extends VerticalLayout {
	protected VerticalLayout contenedor_barra;
	protected HorizontalLayout barra_superior;
	protected Button atrasB;
	protected Label comentarioL;
	protected VerticalLayout usuarioDescripcionLayout;
	protected Image usuarioI;
	protected Label nombreUsuarioL;
	protected Label descripcionL;
	protected VerticalLayout comentarios_layout;
	protected Image usuarioI1;
	protected Label nombreUsuarioL1;
	protected Label comentariosL;
	protected Image usuarioI2;
	protected Label nombreUsuarioL2;
	protected Label comentariosL1;
	protected VerticalLayout menu_inferior_layout;
	protected HorizontalLayout contenedor_horizontal;
	protected HorizontalLayout inicio;
	protected Button paginaPrincipalB;

	public Ver_lista_de_comentarios_ventana() {
		Design.read(this);
	}
}
