package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_lista_de_mis_actividades_ventana extends VerticalLayout {
	protected HorizontalLayout cabecera;
	protected Button configuracionB;
	protected Label nombreUsuarioL;
	protected Image imageI;
	protected Image imageI1;
	protected Image imageI2;
	protected Image imageI3;
	protected Image imageI4;
	protected Image imageI5;
	protected HorizontalLayout menu_inferior;

	public Ver_lista_de_mis_actividades_ventana() {
		Design.read(this);
	}
}
