package MDS2.instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_lista_de_actividades_ventana extends VerticalLayout {
	protected VerticalLayout contenedor_barra;
	protected Button actividadesB;
	protected Button notificacionesB;
	protected VerticalLayout comentarios_layout;
	protected VerticalLayout actividadLayout;
	protected Image verPerfilUsuarioB;
	protected Label nombreUsuarioL;
	protected Label mensajeL;
	protected Image verDetallePublicacionB;
	protected Image verDetallePublicacionB11;
	protected VerticalLayout actividadLayout1;
	protected Image verPerfilUsuarioB1;
	protected Label nombreUsuarioL1;
	protected Label mensajeL1;
	protected Image verDetallePublicacionB1;
	protected VerticalLayout actividadLayout11;
	protected Image verPerfilUsuarioB11;
	protected Label nombreUsuarioL11;
	protected Label mensajeL11;
	protected HorizontalLayout menu_inferior;
	protected Button paginaPrincipalB1;
	protected Button buscarB1;
	protected Button publicarB1;
	protected Button verNotificacionesActividadesB1;
	protected Button verêrfilPropioB;

	public Ver_lista_de_actividades_ventana() {
		Design.read(this);
	}
}
