package MDS2.instagual;

public class Ver_perfil_de_usuario_vista_no_registrado_publica extends Ver_perfil_de_usuario_vista_no_registrado_privada {
	public Usuario _usuario;
	public Ver_lista_de_publicaciones_en_las_que_esta_etiquetado _ver_lista_de_publicaciones_en_las_que_esta_etiquetado;
	public Ver_lista_de_publicaciones_del_usuario _ver_lista_de_publicaciones_del_usuario;
}