package MDS2.instagual;

public class Ver_perfil_de_usuario_vista_no_registrado_lista_de_usuarios_que_dieron_me_gusta extends Ver_perfil_de_usuario_vista_no_registrado_publica {
	public Usuario_que_dio_me_gusta _usuario_que_dio__me_gusta_;
}