package MDS2.instagual;

public class Ver_lista_de_publicaciones_en_las_que_esta_etiquetado_registrado extends Ver_lista_de_publicaciones_en_las_que_esta_etiquetado {
	public Ver_perfil_de_usuario_vista_usuario_registrado _ver_perfil_de_usuario_vista_usuario_registrado;
}